### ISSUE TITLE
Push notifications only received when the app is in background

### ISSUE THREAD

**Issue by epou** [Mosquito-Alert/Mosquito-Alert-Mobile-App#133]
Some users report that they do not receive push notifications when the app is open and in the foreground.

**Comment by aescobarr** [comment]
Is it possible that this is not a bug but expected behaviour? As far as I know, in whatsapp for example there are not push notifications when you receive a message and you are writing.

Maybe the solution could be to show some kind of visual cue inside the app if there are new messages (red dot on the bell icon?)

**Comment by epou** [comment]
For the notification bell, there's already a counter implemented (not yet in production) https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/pull/115

Not sure what is the normal "flow" of the push notifications, makes sense not to show them when the app is in the foreground (not that you mention that is what happens in WhatsApp)

**Comment by DigitalSeneca** [comment]
> Is it possible that this is not a bug but expected behaviour?

Maybe that's expected behavior.
With #115 the notification count is updated when the user opens the app (HomePage) and when the user goes to NotificationPage. If that's acceptable when the app is in foreground, then it's good to go right now once #115 goes into production
