### ISSUE TITLE
Make app open to any adult mosquito species

### ISSUE THREAD

**Issue by JohnPalmer** [Mosquito-Alert/Mosquito-Alert-Mobile-App#17]
Simplify the adult report flow such that the app is no longer focused only on the current 5 targets. This is the first stage in a broader set of changes that we will want to implement for the 2024 season. In this initial stage the idea is to make a very simple change that does not change the data structure. Simply changing the flow of the report screens such that the participant is not pushed away from reporting non-target species.

**Comment by epou** [comment]
@DigitalSeneca Remove "What type of mosquito do you think it was" view  (do not ask for thorax,abdomen,legs either.)

**Comment by DigitalSeneca** [comment]
There is a dependency with the tutorial with screenshots

**Comment by epou** [comment]
@DigitalSeneca, I noticed that #165 has already been merged. However, could the camera layout be adjusted to place the gallery button next to the shutter button (on its right) instead of in the top-right corner? Additionally, it would be ideal if tapping the 'adult' button on the home page directly opened the camera, rather than navigating to the 'attach a photo' form.
