### ISSUE TITLE
iOS message "power intesive app" because of GPS usage

### ISSUE THREAD

**Issue by epou** [Mosquito-Alert/Mosquito-Alert-Mobile-App#47]

**Comment by DigitalSeneca** [comment]
Maybe it makes sense to do a tradeoff and lose location precision in exchange for better power consumption? This option is available for iOS and Android
https://pub.dev/packages/geolocator
![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/83bdee95-5370-4a0a-80b0-e9cf6fdfc111)

**Comment by epou** [comment]
@DigitalSeneca what is the value being used now?

@JohnPalmer what are your thoughts on this? What would be the minimum acceptable location accuracy?

**Comment by DigitalSeneca** [comment]
> @DigitalSeneca what is the value being used now?

Right now it's on high accuracy. But I want to make the distinction that we are now using the dependency flutter_background_geolocation with desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH, and the proposal in my previous message is the package geolocator.

However, it is the same principle: There is a tradeoff between location precision and battery consumption/warnings shown to users

**Comment by JohnPalmer** [comment]
Thanks for your input on this, @DigitalSeneca. I think we need the high accuracy setting for reports: We want to know where these are sent from precisely. Presumably we could reduce the accuracy for the background tracking, since this is masked to 0.025 lon/lat anyway. But there are only 5 of these sampled per day so I wonder how much of an effect that would have on battery drain. I also worry that we would have more errors in the background tracks (meaning the person gets placed into the wrong sampling cell). Also, I assume that the iOS would still flag the app as power intensive since we would have high accuracy set for the reports regardless.

Apart from that, do you recommend geolocator over flutter_background_geolocation?

**Comment by JohnPalmer** [comment]
It would be wonderful if it solves #97 and even better if it also saves power. Thank you!
