### ISSUE TITLE
Use 'geocoding' package for displaying geo information

### ISSUE THREAD

**Issue by epou** [Mosquito-Alert/Mosquito-Alert-Mobile-App#77]
Displaying geo information was removed on the pull request: https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/pull/34

Try to keep displaying that information by using the `placemarkFromCoordinates` from the `geocoding` library. (https://pub.dev/packages/geocoding) package instead.

Things that should display geo information again (that was removed on the pull request):

---

1. Show geo information on report list page.

https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/blob/6c5993a230a86f958c8dca8bcfef2994a6b93ebe/lib/pages/my_reports_pages/my_reports_page.dart#L558

Should append: `"{CITY} ({SUB_ADMIN_AREA})"`

---

2. model `Report.displayCity` should be filled with the CITY name asynchronously.

It's used here: https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/blob/6c5993a230a86f958c8dca8bcfef2994a6b93ebe/lib/pages/my_reports_pages/components/reports_list_widget.dart#L68

**Comment by DigitalSeneca** [comment]
@epou I can't install `geocoding: ^2.1.1` due to dependency incompatibilities with webview_flutter which is used on info_page.dart. That's probably the reason it was removed in the first place.
For now I've tried different combinations but it still can't compile
I tried:
- Remove webview_flutter from dev_dependencies -> It compiles
- Upgrade webview_flutter from 2.8.0 to 3.0.4 -> It compiles
- Upgrade webview_flutter from 3.0.4 to 4+ -> Breaking changes, info_page.dart does not work
- Install geocoding 2.1.1 (latest), 2.0.6 and geocoding 2.0.0 (earliest with null safety) -> Does not work, can't compile with geocoding and webview_flutter at the same time

**Comment by epou** [comment]
So the only way would be upgrading webview_flutter to V4? Maybe it's simple to make it work again even there are breaking changes on the update.

I can help with that if you want.
